Repository PeopleAndService/AlBang-Android, pull requests merged in 2021-12, with the labels that each got.

#40 #14 [epic] develop google login feature
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/albang/AlBangApplication.kt
  app/src/main/java/com/pns/albang/AlBangDataStore.kt
  app/src/main/java/com/pns/albang/LaunchActivity.kt
  app/src/main/java/com/pns/albang/data/User.kt
  app/src/main/java/com/pns/albang/remote/ApiService.kt
  app/src/main/java/com/pns/albang/remote/RemoteDataSource.kt
  app/src/main/java/com/pns/albang/remote/dto/user/SignInRequest.kt
  app/src/main/java/com/pns/albang/remote/dto/user/UpdateNicknameRequest.kt
  app/src/main/java/com/pns/albang/remote/dto/user/UserResponse.kt
  app/src/main/java/com/pns/albang/remote/dto/user/ValidateNicknameResponse.kt
  app/src/main/java/com/pns/albang/repository/UserRepository.kt
  app/src/main/java/com/pns/albang/util/AlBangDataStore.kt
  app/src/main/java/com/pns/albang/util/Event.kt
  app/src/main/java/com/pns/albang/view/LaunchActivity.kt
  app/src/main/java/com/pns/albang/view/LoginActivity.kt
  app/src/main/java/com/pns/albang/viewmodel/LaunchViewModel.kt
  app/src/main/java/com/pns/albang/viewmodel/LoginViewModel.kt
  app/src/main/res/font/nanumsquare_acr.otf
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/dialog_nickname.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: reviewer: yoongyeong, status: review needed

#45 #41 [epic] : NaverMap에 랜드마크 표시 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/albang/MainActivity.kt
  app/src/main/java/com/pns/albang/TestActivity.kt
  app/src/main/java/com/pns/albang/data/Landmark.kt
  app/src/main/java/com/pns/albang/remote/ApiService.kt
  app/src/main/java/com/pns/albang/remote/dto/landmark/AllLandmarkResponse.kt
  app/src/main/java/com/pns/albang/repository/LandmarkRepository.kt
  app/src/main/java/com/pns/albang/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/ic_entry.xml
  app/src/main/res/drawable/ic_guestbook.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_test.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: reviewer: yoongyeong, status: merge needed

#56 [epic] : 내가 쓴 방명록 관리 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/albang/data/MyGuestbook.kt
  app/src/main/java/com/pns/albang/remote/ApiService.kt
  app/src/main/java/com/pns/albang/remote/dto/GetListBasedResponse.kt
  app/src/main/java/com/pns/albang/remote/dto/guestbook/MyGuestbookResponse.kt
  app/src/main/java/com/pns/albang/remote/dto/landmark/LandmarkResponse.kt
  app/src/main/java/com/pns/albang/repository/MyGuestbookRepository.kt
  app/src/main/java/com/pns/albang/view/MyGuestbookActivity.kt
  app/src/main/java/com/pns/albang/view/MyPageActivity.kt
  app/src/main/java/com/pns/albang/view/adapter/CustomBindingAdapter.kt
  app/src/main/java/com/pns/albang/view/adapter/MyGuestbookAdapter.kt
  app/src/main/java/com/pns/albang/viewmodel/MainViewModel.kt
  app/src/main/java/com/pns/albang/viewmodel/MyGuestbookViewModel.kt
  app/src/main/res/layout/activity_my_guestbook.xml
  app/src/main/res/layout/activity_mypage.xml
  app/src/main/res/layout/dialog_delete_guestbook.xml
  app/src/main/res/layout/item_my_guestbook.xml
  app/src/main/res/values/strings.xml
Labels: reviewer: yoongyeong, status: review needed

#64 #61 [epic] : 랜드마크 신청 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/albang/remote/ApiService.kt
  app/src/main/java/com/pns/albang/remote/dto/landmark/LandmarkApplicationRequest.kt
  app/src/main/java/com/pns/albang/repository/LandmarkRepository.kt
  app/src/main/java/com/pns/albang/view/LandmarkApplicationBottomSheet.kt
  app/src/main/java/com/pns/albang/view/MainActivity.kt
  app/src/main/java/com/pns/albang/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/btn_close.xml
  app/src/main/res/drawable/ic_image_holder.xml
  app/src/main/res/layout/dialog_application_landmark.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
Labels: reviewer: yoongyeong, status: merge needed

#66 #65 [feature] : 방명록 작성일시 표시 서식 변경
  app/src/main/java/com/pns/albang/viewmodel/MyGuestbookViewModel.kt
Labels: reviewer: yoongyeong, status: merge needed

#69 #68 [feature] : 방명록 신고/삭제 기능 구현
  app/src/main/java/com/pns/albang/data/Review.kt
  app/src/main/java/com/pns/albang/remote/dto/guestbook/VanRequest.kt
  app/src/main/java/com/pns/albang/view/ReviewActivity.kt
  app/src/main/java/com/pns/albang/view/adapter/ReviewAdapter.kt
  app/src/main/java/com/pns/albang/viewmodel/ReviewViewModel.kt
Labels: reviewer: yoongyeong, status: review needed

#70 [epic] 리뷰 페이지 완성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/albang/Review.kt
  app/src/main/java/com/pns/albang/ReviewActivity.kt
  app/src/main/java/com/pns/albang/data/Review.kt
  app/src/main/java/com/pns/albang/remote/ApiService.kt
  app/src/main/java/com/pns/albang/remote/dto/guestbook/ReviewRequest.kt
  app/src/main/java/com/pns/albang/remote/dto/guestbook/ReviewResponse.kt
  app/src/main/java/com/pns/albang/remote/dto/guestbook/VanRequest.kt
  app/src/main/java/com/pns/albang/repository/ReviewRepository.kt
  app/src/main/java/com/pns/albang/util/CustomBindingAdapter.kt
  app/src/main/java/com/pns/albang/view/MainActivity.kt
  app/src/main/java/com/pns/albang/view/ReviewActivity.kt
  app/src/main/java/com/pns/albang/view/adapter/ReviewAdapter.kt
  app/src/main/java/com/pns/albang/viewmodel/ReviewViewModel.kt
  app/src/main/res/drawable/sample_image.png
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/item_review.xml
  app/src/main/res/xml/activity_review_scene.xml
Labels: epic, reviewer: suho, status: merge needed

#76 [Epic] AR Review Page
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/albang/data/Review.kt
  app/src/main/java/com/pns/albang/view/ARReviewActivity.kt
  app/src/main/java/com/pns/albang/view/CloudAnchorFragment.kt
  app/src/main/java/com/pns/albang/view/MainActivity.kt
  app/src/main/java/com/pns/albang/view/ReviewActivity.kt
  app/src/main/java/com/pns/albang/viewmodel/ReviewARViewModel.kt
  app/src/main/java/com/pns/albang/viewmodel/ReviewViewModel.kt
  app/src/main/res/layout/activity_ar_review.xml
  app/src/main/res/layout/dialog_review.xml
  app/src/main/res/layout/view_ar_review.xml
  app/src/main/res/values/strings.xml
Labels: epic, reviewer: suho, status: merge needed
